language: objective-c
osx_image: xcode11.3
sudo: false
before_install:
  - gem install xcpretty
install:
  - chmod u+x Scripts/travis-set-constants.sh
  - Scripts/travis-set-constants.sh 
  - bundle install
env:
  matrix:
    - XCODE_SCHEME="libPusher" SDK="iphonesimulator" DESTINATION="OS=13.3,name=iPhone 11" ADDITIONAL_ARGUMENTS=""
    - XCODE_SCHEME="libPusher-OSX" SDK="macosx" DESTINATION="arch=x86_64" ADDITIONAL_ARGUMENTS="MACOSX_DEPLOYMENT_TARGET=10.9"
    - XCODE_SCHEME="Functional Specs" SDK="iphonesimulator" DESTINATION="OS=13.3,name=iPhone 11" ADDITIONAL_ARGUMENTS=""
script:
  - set -o pipefail
  - rackup -p 9292 Scripts/auth_server.ru > logs.txt 2>&1 &
  - xcodebuild -workspace libPusher.xcworkspace -scheme "$XCODE_SCHEME" -sdk "$SDK" test -destination "$DESTINATION" $ADDITIONAL_ARGUMENTS | xcpretty -tc
